import { HorizontalBox, LineEdit } from "std-widgets.slint";

export struct UIOption {
    name: string,
    display: string,
    value: string,
}

export component LabeledLineEdit {
    in property <string> label: "Label";
    in-out property <string> text: "Default Value";
    callback line_edited(text: string);
    callback text_modified(text: string);
    HorizontalBox {
        Text {
            text: "\{root.label}";
            vertical-alignment: TextVerticalAlignment.center;
        }
        LineEdit {
            text <=> root.text;
            changed has-focus => {
                if (self.has-focus != true) {
                    line_edited(text);
                }
            }
            edited(text) => {
                text_modified(text)
            }
        }
    }
}

export component DynamicForm {
    in property <[UIOption]> options;
    in-out property <[UIOption]> edited: options;
    callback option_edited(index: int, new_value: string);
    VerticalLayout {
        for opt[index] in edited: LabeledLineEdit {
            label: opt.display;
            text: opt.value;

            line_edited(text) => {
                option_edited(index, text);
            }

            text_modified(text) => {
                edited[index].value = text;
            }
        }
    }
}