import { HorizontalBox, LineEdit, CheckBox, ComboBox } from "std-widgets.slint";

export component LabeledLineEdit {
    in property <string> label: "Label";
    in-out property <string> text: "Default Value";
    callback line_edited(text: string);
    callback text_modified(text: string);
    width: 100%;
    HorizontalBox {
        Text {
            text: "\{root.label}";
            vertical-alignment: TextVerticalAlignment.center;
        }
        LineEdit {
            text <=> root.text;
            changed has-focus => {
                if (self.has-focus != true) {
                    line_edited(text);
                }
            }
            edited(text) => {
                text_modified(text)
            }
        }
    }
}

export component LabledCheckBox {
    in property <string> label: "Label";
    in-out property <bool> checked: false;
    callback changed(new_val: string);
    HorizontalBox {
        Text {
            text: "\{root.label}";
            vertical-alignment: TextVerticalAlignment.center;
        }
        CheckBox {
            checked <=> checked;
            toggled() => {
                changed(self.checked ? "true" : "false")
            }
        }
    }
}

export component LabeledComboBox {
    in property <string> label: "Label";
    in property <[string]> options: ["first", "second", "third"];
    in-out property <string> current_value: "";
    callback changed (new_val: string);
    HorizontalBox {
        Text {
            text: "\{root.label}";
            vertical-alignment: TextVerticalAlignment.center;
        }
        ComboBox {
            model: root.options;
            current-value <=> root.current_value;
            selected(value) => {
                changed(value);
            }
        }
    }
}
