import { LabeledLineEdit, LabledCheckBox, LabeledComboBox } from "common-components.slint";

export enum UIType {
    Text,
    Checkbox,
    ComboBox
}

export struct UIOption {
    name: string,
    display: string,
    value: string,
    type: UIType,
    options: [string],
}

export component DynamicField {
    in property <UIOption> option;
    in property <int> index;

    callback edited(index: int, new_value: string);
    callback modified(index: int, new_value: string);

    min-height: 40px;
    min-width: 300px;

    if option.type == UIType.Text: LabeledLineEdit {
        label: option.display;
        text: option.value;

        line_edited(text) => {
            edited(root.index, text);
        }

        text_modified(text) => {
            modified(root.index, text);
        }
    }
    if option.type == UIType.Checkbox: LabledCheckBox {
        label: option.display;
        checked: option.value == "true" ? true : false;

        changed(new-val) => {
            modified(root.index, new-val);
            edited(root.index, new-val);
        }
    }
    if option.type == UIType.ComboBox: LabeledComboBox {
        label: option.display;
        current_value: option.value;
        options: option.options;

        changed(new-val) => {
            modified(root.index, new-val);
            edited(root.index, new-val);
        }
    }
}

export component DynamicForm {
    in property <[UIOption]> options;
    in-out property <[UIOption]> edited: options;
    callback option_edited(index: int, new_value: string);
    VerticalLayout {
        for opt[index] in edited: DynamicField {
            option: opt;
            index: index;

            edited(index, text) => {
                option_edited(index, text);
            }

            modified(index, text) => {
                edited[index].value = text;
            }
        }
    }
}